-- AlterTable
ALTER TABLE "AiDraft" ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMPTZ;

-- AlterTable
ALTER TABLE "ApricotSession" ALTER COLUMN "updatedAt" SET DATA TYPE TIMESTAMPTZ;

-- AlterTable
ALTER TABLE "AuditLog" ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMPTZ;

-- AlterTable
ALTER TABLE "AvailabilitySlot" ALTER COLUMN "syncedAt" SET DATA TYPE TIMESTAMPTZ;

-- AlterTable
ALTER TABLE "BookingRequest" ALTER COLUMN "handledAt" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMPTZ;

-- AlterTable
ALTER TABLE "Conversation" ALTER COLUMN "lastInboundAt" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "lastMessageAt" SET DATA TYPE TIMESTAMPTZ;

-- AlterTable
ALTER TABLE "Message" ALTER COLUMN "waTimestamp" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMPTZ;

-- AlterTable
ALTER TABLE "WebhookEvent" ALTER COLUMN "receivedAt" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "processedAt" SET DATA TYPE TIMESTAMPTZ;
